# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2837299ff887c7f63b1590f0ac3bcee77f7783c043301e43be466d0927e0eda80fbd9b6c7ad2ec529d64a03cdad6d65c75ef57aac7d4006f6a13ac81b77d820

test:
  secret_key_base: 67552f764cc22dc45597275baafbaab64346b4d894160e33a36765a09ea39c35db19e36abbeb422964d227bcac53dfc355f2190bcdaa26e1b9f1246749cc7eba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
